/* eslint-disable @typescript-eslint/naming-convention */

export const pflanzen = [
    {
        _id: '00000000-0000-0000-0000-000000000001',
        name: 'Alocasia',
        wuchshoehe: 4,
        pflanzentyp: 'GARTENPFLANZE',
        versandart: 'VERSAND',
        preis: 11.1,
        rabatt: 0.011,
        lieferbar: true,
        artikelnummer: '000-0000000001',
        herkunft: 'Subtropical Asia to Eastern Australia',
        schlagwoerter: ['Immergrün'],
        zulieferer: [
            {
                name: 'Dehner',
                homepage: 'https://www.dehner.de/',
            },
            {
                name: 'Hornbach',
                homepage: 'https://www.hornbach.de/',
            },
        ],
        __v: 0,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        _id: '00000000-0000-0000-0000-000000000002',
        name: 'Monstera',
        wuchshoehe: 2,
        pflanzentyp: 'ZIMMERPFLANZE',
        versandart: 'SELBSTABHOLUNG',
        preis: 22.2,
        rabatt: 0.022,
        lieferbar: true,
        artikelnummer: '000-0000000002',
        herkunft: 'Tropical regions of the Americas',
        schlagwoerter: ['Fensterblatt'],
        zulieferer: [
            {
                name: 'Dehner',
                homepage: 'https://www.dehner.de/',
            },
        ],
        __v: 0,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        _id: '00000000-0000-0000-0000-000000000003',
        name: 'Rosmarin ',
        wuchshoehe: 1,
        pflanzentyp: 'NUTZPFLANZE',
        versandart: 'VERSAND',
        preis: 33.3,
        rabatt: 0.033,
        lieferbar: true,
        artikelnummer: '000-0000000003',
        herkunft: 'Mediterranean and Asia',
        schlagwoerter: ['Kräuter', 'Lecker'],
        zulieferer: [
            {
                name: 'Urban Jungle',
                homepage: 'https://www.urban-jungle.store/',
            },
        ],
        __v: 0,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        _id: '00000000-0000-0000-0000-000000000004',
        name: 'Syngonium',
        wuchshoehe: 3,
        pflanzentyp: 'ZIMMERPFLANZE',
        versandart: 'OUT_OF_STOCK',
        preis: 44.4,
        rabatt: 0.044,
        lieferbar: true,
        artikelnummer: '000-0000000004',
        herkunft: 'Tropical rain forests in southern Mexico',
        schlagwoerter: [],
        zulieferer: [
            {
                name: 'Hornbach',
                homepage: 'https://www.hornbach.de/',
            },
        ],
        __v: 0,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        _id: '00000000-0000-0000-0000-000000000005',
        name: 'Blumenkohl',
        wuchshoehe: 2,
        pflanzentyp: 'NUTZPFLANZE',
        versandart: 'OUT_OF_STOCK',
        preis: 55.5,
        rabatt: 0.055,
        lieferbar: true,
        artikelnummer: '000-0000000005',
        herkunft: 'Anatolien ',
        schlagwoerter: ['Lecker', 'Weiß'],
        zulieferer: [
            {
                name: 'Urban Jungle',
                homepage: 'https://www.urban-jungle.store/',
            },
        ],
        __v: 0,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
];

/* eslint-enable @typescript-eslint/naming-convention */
